import random # import random module to enable random functionality for my program
words = [
    "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after", "again", 
    "agent", "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone", 
    "along", "alter", "among", "anger", "angle", "angry", "apart", "apple", "apply", "arena", 
    "argue", "arise", "array", "aside", "asset", "audio", "audit", "avoid", "award", "aware", 
    "badly", "baker", "bases", "basic", "basis", "beach", "beard", "beast", "begin", "being", 
    "below", "bench", "billy", "birth", "black", "blade", "blame", "blast", "blend", "block", 
    "blood", "board", "boast", "bonus", "boost", "bound", "brain", "brand", "bread", "break", 
    "breed", "brief", "bring", "broad", "broke", "brown", "build", "built", "buyer", "cable", 
    "calmly", "canal", "carry", "catch", "cause", "chain", "chair", "chart", "chase", "cheap", 
    "check", "chest", "chief", "child", "china", "choir", "civil", "claim", "class", "clean", 
    "clear", "climb", "clock", "close", "coach", "coast", "could", "count", "court", "cover", 
    "craft", "crash", "cream", "crime", "cross", "crowd", "crown", "curve", "cycle", "daily", 
    "dance", "dated", "dealt", "death", "debut", "delay", "depth", "doing", "doubt", "dozen", 
    "draft", "drama", "drawn", "dream", "dress", "drill", "drink", "drive", "drove", "dying", 
    "eager", "early", "earth", "eight", "elite", "empty", "enemy", "enjoy", "enter", "entry"
] # list of words used for wordle
# initializing attempts and score variables 
attempts = 6
score = 0

def wordle():
    global attempts, score # using global so attempts and score can be used in the function
    word = random.choice(words) # program will pick a random word from words
    while attempts != 0:
        guess = input(f"Guess the 5 letter word! ({attempts} attempts remaining) ")

        if len(guess) != 5: # checking if users input is 5 letters long
            print("Your guess must be 5 letters long!")
            return
        
        if guess == word: 
            score += 1
            print(f"Correct! The word was {word}. Your score is {score}!")
            attempts = 6
            return True

        else:
            print(f"Your guess is incorrect!")
            attempts -= 1
            for i in guess: # telling the user if their guess contains the same letters found in the word and at what index like real wordle
                if i in word:
                    print(f"{i} is in your guess at index {word.index(i)}")

        if attempts == 0: # if user fails to get the word, game will end 
            print(f"Game over! The word was {word}. Your score was {score}.")
            return False

while True:
    if not wordle(): # checking if wordle returns false from failing to guess the word, if it does the game will end
        break
    else:
        keep_playing = input("Do you want to keep playing? (y/n) ") # asking user if they want to keep playing after each round
        if keep_playing.lower() != 'y': # game ends if user does not input y
            print(f"Thank you for playing! Your final score was {score}.")
            break


# words list generated by Gemini